import { from } from 'rxjs'

// AUTHORIZATION
export * from './dto/auth/registr_user.dto'
export * from './dto/auth/login_user.dto'
export * from './dto/auth/create_role.dto'
export * from './outputs/object-operation.output'
export * from './dto/auth/add_user_role.dto'
export * from './dto/auth/update_user.dto'
export * from './dto/auth/update_role.dto'
export * from './dto/auth/create_access.dto'
export * from './dto/auth/update_access.dto'
export * from './dto/auth/add_user_access.dto'
export * from './dto/auth/create_user.dto'

// TIMETABLE
export * from './dto/timetable/create_user_info.dto'
// -- CREATE
export * from './dto/timetable/create_auditorium.dto'
export * from './dto/timetable/create_cts.dto'
export * from './dto/timetable/create_discipline.dto'
export * from './dto/timetable/create_discipline_type.dto'
export * from './dto/timetable/create_edit_timetable.dto'
export * from './dto/timetable/create_full_timetable.dto'
export * from './dto/timetable/create_full_timetable.dto'
export * from './dto/timetable/create_group.dto'
export * from './dto/timetable/create_load_teach.dto'
export * from './dto/timetable/create_maket_timetable.dto'
export * from './dto/timetable/create_speciality.dto'
export * from './dto/timetable/create_student.dto'
export * from './dto/timetable/create_teacher.dto'

// -- UPDATE
export * from './dto/timetable/update_auditorium.dto'
export * from './dto/timetable/update_cts.dto'
export * from './dto/timetable/update_discipline.dto'
export * from './dto/timetable/update_discipline_type.dto'
export * from './dto/timetable/update_edit_timetable.dto'
export * from './dto/timetable/update_full_timetable.dto'
export * from './dto/timetable/update_full_timetable.dto'
export * from './dto/timetable/update_group.dto'
export * from './dto/timetable/update_load_teach.dto'
export * from './dto/timetable/update_maket_timetable.dto'
export * from './dto/timetable/update_speciality.dto'
export * from './dto/timetable/update_student.dto'
export * from './dto/timetable/update_teacher.dto'

